/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import enumerations.EstadosBrazil;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelos.Cliente_PessoaFisica;
import modelos.auxiliares.Endereco;
import persistencia.ManipulaBancoClientePEssoaFisica;

/**
 *
 * @author tanak
 */
public class CadastroDeCliente extends javax.swing.JFrame {

    ArrayList<Cliente_PessoaFisica> listaClientes = new ArrayList<>();

    /**
     * Creates new form CadastroDeCliente
     */
    public CadastroDeCliente() {
        initComponents();
        loadComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tField_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tField_cpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tField_telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tField_TipoLogradouro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tField_email = new javax.swing.JTextField();
        btn_criarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tArea_saida = new javax.swing.JTextArea();
        tField_DataNascimento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tField_Logradouro = new javax.swing.JTextField();
        tField_Numero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tField_Complemento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tField_Bairro = new javax.swing.JTextField();
        tField_Cidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cb_Estado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        tField_CEP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));
        getContentPane().add(tField_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 430, -1));

        jLabel2.setText("CPF: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));
        getContentPane().add(tField_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 160, -1));

        jLabel3.setText("Telefone: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));
        getContentPane().add(tField_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 160, -1));

        jLabel4.setText("Tipo Logradouro:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, 20));
        getContentPane().add(tField_TipoLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 160, -1));

        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));
        getContentPane().add(tField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 210, -1));

        btn_criarCliente.setText("Criar Cliente");
        btn_criarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_criarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 137, 44));

        tArea_saida.setColumns(20);
        tArea_saida.setRows(5);
        jScrollPane1.setViewportView(tArea_saida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 490, 120));
        getContentPane().add(tField_DataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 50, 145, -1));

        jLabel6.setText("Data de Nascimento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel7.setText("Logradouro");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 32));
        getContentPane().add(tField_Logradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, -1));
        getContentPane().add(tField_Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 60, -1));

        jLabel8.setText("Nº:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 18, -1));

        jLabel9.setText("Complemento:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        getContentPane().add(tField_Complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 480, -1));

        jLabel10.setText("Bairro:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 36, -1));

        jLabel11.setText("Cidade:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, -1));
        getContentPane().add(tField_Bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 160, -1));
        getContentPane().add(tField_Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, -1));

        jLabel12.setText("Estado:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 51, -1));

        getContentPane().add(cb_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 110, 110, -1));

        jLabel13.setText("CEP:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));
        getContentPane().add(tField_CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 140, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_criarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarClienteActionPerformed
        try {
            String nome = tField_nome.getText();
            /*    
            private String complemento;
            private String bairro;
            private String cidade;
            private EstadosBrazil estado;
            private String CEP;*/
            String cpf = tField_cpf.getText();
            String telefone = tField_telefone.getText();
            String tipoLogradouro = tField_TipoLogradouro.getText();
            String logradoro = tField_Logradouro.getText();
            String numero = tField_Numero.getText();
            String complemento = tField_Complemento.getText();
            String bairro = tField_Bairro.getText();
            String cidade = tField_Cidade.getText();
            String estado = cb_Estado.getSelectedItem().toString();
            String CEP = tField_CEP.getText();
            String auxDataNascimento = tField_DataNascimento.getText();
            String[] vetDataNascimento = auxDataNascimento.split("/");
            Date dataNascimento = new Date(Integer.parseInt(vetDataNascimento[2]) - 1900, Integer.parseInt(vetDataNascimento[1]) - 1, Integer.parseInt(vetDataNascimento[0]));
            String email = tField_email.getText();

            EstadosBrazil eb = Enum.valueOf(EstadosBrazil.class, estado);

            Endereco endereco = new Endereco(tipoLogradouro, logradoro, numero, complemento, bairro, cidade, eb, CEP);
            Cliente_PessoaFisica clPF = new Cliente_PessoaFisica(nome, cpf, dataNascimento, telefone, email, endereco);
            new ManipulaBancoClientePEssoaFisica().incluir(clPF);
            //criando novo cliente com o id correspondente
            //Cliente_PessoaFisica clienteParaAdicionar = new Cliente_PessoaFisica(nome, cpf, endereco, telefone, email);
            //Cliente_PessoaFisica cliPF = new Cliente_PessoaFisica(nome, cpf, dataNascimento, telefone, email, endereco);
            StringBuffer saida = new StringBuffer("Cliente criado com sucesso");
            saida.append("Dados do novo cliente: ");
//            saida.append(clienteParaAdicionar.getNome()).append("\n");
//            saida.append(clienteParaAdicionar.getCpf()).append("\n");
//            saida.append(clienteParaAdicionar.getTelefone()).append("\n");
//            saida.append(clienteParaAdicionar.getEndereco()).append("\n");
//            saida.append(clienteParaAdicionar.getEmail()).append("\n");

//            listaClientes.add(clienteParaAdicionar);
            tArea_saida.setText(String.valueOf(saida));
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_btn_criarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeCliente().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_criarCliente;
    private javax.swing.JComboBox<EstadosBrazil> cb_Estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tArea_saida;
    private javax.swing.JTextField tField_Bairro;
    private javax.swing.JTextField tField_CEP;
    private javax.swing.JTextField tField_Cidade;
    private javax.swing.JTextField tField_Complemento;
    private javax.swing.JTextField tField_DataNascimento;
    private javax.swing.JTextField tField_Logradouro;
    private javax.swing.JTextField tField_Numero;
    private javax.swing.JTextField tField_TipoLogradouro;
    private javax.swing.JTextField tField_cpf;
    private javax.swing.JTextField tField_email;
    private javax.swing.JTextField tField_nome;
    private javax.swing.JTextField tField_telefone;
    // End of variables declaration//GEN-END:variables

    private void loadComboBox() {
        cb_Estado.setModel(new DefaultComboBoxModel<>(EstadosBrazil.values()));
    }
}
