/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelos.auxiliares.MarcaVeiculo;
import persistencia.ManipulaBancoMarca;

/**
 *
 * @author witorsather
 */
public class TelaCadastroDeMarcas extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroDeMarcas
     */
    public TelaCadastroDeMarcas() {
        initComponents();
        try {
            loadTableMarcas();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
        
        jButtonVoltar.setVisible(false);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldIncluirMarca = new javax.swing.JTextField();
        jButtonIncluirMarca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMarcasExistentes = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        setTitle("Marcas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextFieldIncluirMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 325, 471, -1));

        jButtonIncluirMarca.setBackground(new java.awt.Color(0, 204, 255));
        jButtonIncluirMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-mais-2-matemática-verde-30.png"))); // NOI18N
        jButtonIncluirMarca.setText("INCLUIR");
        jButtonIncluirMarca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonIncluirMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIncluirMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 110, 50));

        jLabel1.setText("CADASTRO DE MARCAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 6, -1, 15));

        jLabel2.setText("MARCAS EXISTENTES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, -1, -1));

        jTableMarcasExistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMarcasExistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMarcasExistentesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMarcasExistentes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, 625, 218));

        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, 13));

        jButtonRemover.setBackground(new java.awt.Color(0, 204, 255));
        jButtonRemover.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-excluir-30.png"))); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 110, 50));

        jButtonEditar.setBackground(new java.awt.Color(0, 204, 255));
        jButtonEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-lápis-30.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirMarcaActionPerformed
        try {
            new ManipulaBancoMarca().incluir(new MarcaVeiculo(jTextFieldIncluirMarca.getText()));
            jTextFieldIncluirMarca.setText("");
            loadTableMarcas();
            //jLabelCriadoComSucesso.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonIncluirMarcaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaCadastroDeVeiculo janelaNova = new TelaCadastroDeVeiculo();
        janelaNova.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTableMarcasExistentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMarcasExistentesMouseClicked
        // TODO add your handling code here:
        try {
            int indexSelecionado = jTableMarcasExistentes.getSelectedRow();
            
            if(indexSelecionado >= 0) {
                String marcaSelecionada = String.valueOf(jTableMarcasExistentes.getValueAt(indexSelecionado,0));
                
                MarcaVeiculo marcaObjSelecionado = new ManipulaBancoMarca().buscar(new ManipulaBancoMarca().buscar(marcaSelecionada));
                
                jTextFieldIncluirMarca.setText(marcaObjSelecionado.getNomeMarca());
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jTableMarcasExistentesMouseClicked

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        try {
            int indexTabela = jTableMarcasExistentes.getSelectedRow();
            if (indexTabela < 0) {
                JOptionPane.showMessageDialog(rootPane, "Selecione, na tabela qual marca deseja remover");
            } else {
                int confirmação = JOptionPane.showConfirmDialog(rootPane, "Remover?");
                //  * 0 se for sim, 1 se for não, 2 se for cancelar

                if (confirmação == 0) {//   * caso tenha confirmado a exclusão
                    String marcaParaExclusao = String.valueOf(jTableMarcasExistentes.getValueAt(jTableMarcasExistentes.getSelectedRow(),0));
                    int idMarcaParaExclusao = new ManipulaBancoMarca().buscar(marcaParaExclusao);
                    if(idMarcaParaExclusao != 0){
                        new ManipulaBancoMarca().remover(idMarcaParaExclusao);
                    }
                    
                } else {//    * cancelar
                    //  * pass
                }
            }
            loadTableMarcas();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            int indexTabela = jTableMarcasExistentes.getSelectedRow();
            if (indexTabela < 0) {
                JOptionPane.showMessageDialog(rootPane, "Selecione, na tabela qual marca deseja editar");
            } else {
                
                String marca = jTextFieldIncluirMarca.getText();

                ManipulaBancoMarca mb = new ManipulaBancoMarca();
                String marcaParaExclusao = String.valueOf(jTableMarcasExistentes.getValueAt(jTableMarcasExistentes.getSelectedRow(), 0));
                int idMarcaParaExclusao = mb.buscar(marcaParaExclusao);
                
                MarcaVeiculo marcaInserir = new MarcaVeiculo(marca);
                
                mb.editar(idMarcaParaExclusao, marcaInserir);
                
                JOptionPane.showMessageDialog(rootPane, "Editado");
                loadTableMarcas();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void loadTableMarcas() throws Exception {
        DefaultTableModel dtb = new DefaultTableModel(new Object[]{"Marcas existentes: "}, 0);
        ArrayList<MarcaVeiculo> listaMarcas = new ManipulaBancoMarca().buscarTodos();
        for (MarcaVeiculo m : listaMarcas) {
            dtb.addRow(new Object[]{m.getNomeMarca()});
        }
        jTableMarcasExistentes.setModel(dtb);
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTableMarcasExistentes.getModel());
        jTableMarcasExistentes.setRowSorter(sorter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonIncluirMarca;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMarcasExistentes;
    private javax.swing.JTextField jTextFieldIncluirMarca;
    // End of variables declaration//GEN-END:variables
}
