/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelos.auxiliares.MarcaVeiculo;
import modelos.auxiliares.ModeloVeiculo;
import persistencia.ManipulaBancoMarca;
import persistencia.ManipulaBancoModelos;

/**
 *
 * @author witorsather
 */
public class TelaCadastroModelos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroModelos
     */
    public TelaCadastroModelos() {
        initComponents();
        jLabel1.setVisible(false);
        loadTableModelos();
        loadComboBoxMarcas();
        jButtonCriarModelo.setEnabled(false);
        jButtonVoltar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModelos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonCriarModelo = new javax.swing.JButton();
        jTextFieldModelo = new javax.swing.JTextField();
        jComboBoxMarcas = new javax.swing.JComboBox<>();
        jButtonVoltar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();

        setTitle("Modelos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome modelo", "Nome marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableModelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableModelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableModelos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 440, 275));

        jLabel1.setText("Modelo criado com sucesso!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 287, -1, -1));

        jButtonCriarModelo.setBackground(new java.awt.Color(0, 204, 255));
        jButtonCriarModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-mais-2-matemática-verde-30.png"))); // NOI18N
        jButtonCriarModelo.setText("Incluir");
        jButtonCriarModelo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCriarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarModeloActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCriarModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 110, 50));

        jTextFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 309, 239, -1));

        jComboBoxMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcasActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 337, 239, -1));

        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 365, -1, 12));

        jButtonEditar.setBackground(new java.awt.Color(0, 204, 255));
        jButtonEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-lápis-30.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 110, 50));

        jButtonRemover.setBackground(new java.awt.Color(0, 204, 255));
        jButtonRemover.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-excluir-30.png"))); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCriarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarModeloActionPerformed
        try {
            int idMarca = new ManipulaBancoMarca().buscar(String.valueOf(jComboBoxMarcas.getSelectedItem()));
            new ManipulaBancoModelos().incluir(new ModeloVeiculo(jTextFieldModelo.getText(), idMarca));
            loadTableModelos();
            jLabel1.setVisible(true);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonCriarModeloActionPerformed

    private void jTextFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloActionPerformed

    private void jComboBoxMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcasActionPerformed
        if (jComboBoxMarcas.getSelectedIndex() > 0) {
            jButtonCriarModelo.setEnabled(true);
        } else {
            jButtonCriarModelo.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxMarcasActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        new TelaCadastroDeVeiculo().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            int indexTabela = jTableModelos.getSelectedRow();
            if (indexTabela < 0) {
                JOptionPane.showMessageDialog(rootPane, "Selecione, na tabela qual marca deseja editar");
            } else {
                if (jComboBoxMarcas.getSelectedIndex() == 0) {//  * mão escolheu a marca
                    JOptionPane.showMessageDialog(rootPane, "Selecione, na tabela qual marca deseja editar");
                    return;
                }
                String modelo = jTextFieldModelo.getText();

                ManipulaBancoModelos mb = new ManipulaBancoModelos();
                String modeloParaExclusao = String.valueOf(jTableModelos.getValueAt(jTableModelos.getSelectedRow(), 0));
                int idModeloParaExclusao = mb.buscar(modeloParaExclusao);
                int idMarca = new ManipulaBancoMarca().buscar("" + jComboBoxMarcas.getSelectedItem());

                ModeloVeiculo modeloInserir = new ModeloVeiculo(modelo, idMarca);

                mb.editar(idModeloParaExclusao, modeloInserir);

                JOptionPane.showMessageDialog(rootPane, "Editado");
                loadTableModelos();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        try {
            int indexTabela = jTableModelos.getSelectedRow();
            if (indexTabela < 0) {
                JOptionPane.showMessageDialog(rootPane, "Selecione, na tabela qual marca deseja remover");
            } else {
                int confirmação = JOptionPane.showConfirmDialog(rootPane, "Remover?");
                //  * 0 se for sim, 1 se for não, 2 se for cancelar

                if (confirmação == 0) {//   * caso tenha confirmado a exclusão
                    String modeloParaExclusao = String.valueOf(jTableModelos.getValueAt(jTableModelos.getSelectedRow(), 0));
                    int idModeloParaExclusao = new ManipulaBancoModelos().buscar(modeloParaExclusao);
                    if (idModeloParaExclusao != 0) {
                        new ManipulaBancoModelos().remover(idModeloParaExclusao);
                    }

                } else {//    * cancelar
                    //  * pass
                }
            }
            loadTableModelos();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jTableModelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableModelosMouseClicked
        // TODO add your handling code here:
        try {
            int indexSelecionado = jTableModelos.getSelectedRow();

            if (indexSelecionado >= 0) {
                String modeloSelecionada = String.valueOf(jTableModelos.getValueAt(indexSelecionado, 0));
                String marcaSelecionada = String.valueOf(jTableModelos.getValueAt(indexSelecionado, 1));

                ModeloVeiculo modeloObjSelecionado = new ManipulaBancoModelos().buscar(new ManipulaBancoModelos().buscar(modeloSelecionada));

                MarcaVeiculo marcaObj = new ManipulaBancoMarca().buscar(new ManipulaBancoMarca().buscar(marcaSelecionada));

                jTextFieldModelo.setText(modeloObjSelecionado.getNomeModelo());
                jComboBoxMarcas.setSelectedItem(marcaObj.getNomeMarca());
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jTableModelosMouseClicked

    private void loadTableModelos() {
        try {
            DefaultTableModel table = (DefaultTableModel) jTableModelos.getModel();
            table.setRowCount(0);
            ArrayList<ModeloVeiculo> listaModelos = new ManipulaBancoModelos().buscarTodos();

            for (ModeloVeiculo m : listaModelos) {
                MarcaVeiculo marca = new ManipulaBancoMarca().buscar(m.getIdMarca());
                if (marca != null) {
                    table.addRow(new Object[]{m.getNomeModelo(), marca.getNomeMarca()});
                } else {
                    new Exception("marca com o ID: " + m.getIdMarca() + " não encontrada").printStackTrace();
//  * marca não encontrada
                }
            }

            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTableModelos.getModel());
            jTableModelos.setRowSorter(sorter);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }

    private void loadComboBoxMarcas() {
        try {
            ArrayList<MarcaVeiculo> listaMarcas = new ManipulaBancoMarca().buscarTodos();
            String[] marcas = new String[listaMarcas.size() + 1];
            marcas[0] = "--MARCAS--";

            for (int i = 1; i < marcas.length; i++) {
                marcas[i] = listaMarcas.get(i - 1).getNomeMarca();
            }
            jComboBoxMarcas.setModel(new DefaultComboBoxModel<>(marcas));
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarModelo;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModelos;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables
}
