/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import enumerations.EstadosBrazil;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelos.PessoaFisica;
import modelos.auxiliares.Endereco;
import persistencia.ManipulaBancoPessoaFisica;

/**
 *
 * @author ALUNO
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaCadastroCliente() {
        initComponents();
        loadComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_TipoPessoa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tField_nome = new javax.swing.JTextField();
        jLabel_CPF_CNPJ = new javax.swing.JLabel();
        tField_cpf_cnpj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tField_telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tField_TipoLogradouro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tField_email = new javax.swing.JTextField();
        btn_criarCliente = new javax.swing.JButton();
        tField_DataNascimento = new javax.swing.JTextField();
        jLabel_DtNasc_RazSoc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tField_Logradouro = new javax.swing.JTextField();
        tField_Numero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tField_Complemento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tField_Bairro = new javax.swing.JTextField();
        tField_Cidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cb_Estado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        tField_CEP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tField_telefone1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tField_telefone2 = new javax.swing.JTextField();
        jRadioButton_PessoaFisica = new javax.swing.JRadioButton();
        jRadioButton_PessoaJuridica = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));
        getContentPane().add(tField_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 420, -1));

        jLabel_CPF_CNPJ.setText("CPF: ");
        getContentPane().add(jLabel_CPF_CNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 20));
        getContentPane().add(tField_cpf_cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, -1));

        jLabel3.setText("Celular:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));
        getContentPane().add(tField_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, -1));

        jLabel4.setText("Tipo Logradouro:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, 20));
        getContentPane().add(tField_TipoLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 160, -1));

        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        getContentPane().add(tField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, -1));

        btn_criarCliente.setText("Criar Cliente");
        btn_criarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_criarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 137, 44));
        getContentPane().add(tField_DataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 140, 145, -1));

        jLabel_DtNasc_RazSoc.setText("Data de Nascimento:");
        getContentPane().add(jLabel_DtNasc_RazSoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel7.setText("Logradouro");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 32));
        getContentPane().add(tField_Logradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 210, -1));
        getContentPane().add(tField_Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 60, -1));

        jLabel8.setText("Nº:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 18, -1));

        jLabel9.setText("Complemento:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));
        getContentPane().add(tField_Complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 480, -1));

        jLabel10.setText("Bairro:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 36, -1));

        jLabel11.setText("Cidade:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        getContentPane().add(tField_Bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 150, -1));
        getContentPane().add(tField_Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 150, -1));

        jLabel12.setText("Estado:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 51, -1));

        getContentPane().add(cb_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 110, -1));

        jLabel13.setText("CEP:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));
        getContentPane().add(tField_CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 110, -1));

        jLabel14.setText("Residencial:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 20));
        getContentPane().add(tField_telefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 180, -1));

        jLabel15.setText("Comercial:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 20));
        getContentPane().add(tField_telefone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 150, -1));

        buttonGroup_TipoPessoa.add(jRadioButton_PessoaFisica);
        jRadioButton_PessoaFisica.setSelected(true);
        jRadioButton_PessoaFisica.setText("Pessoa Fisica");
        getContentPane().add(jRadioButton_PessoaFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        buttonGroup_TipoPessoa.add(jRadioButton_PessoaJuridica);
        jRadioButton_PessoaJuridica.setText("Pessoa Juridica");
        getContentPane().add(jRadioButton_PessoaJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_criarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarClienteActionPerformed
        try {
            String nome = tField_nome.getText();
            /*
            private String complemento;
            private String bairro;
            private String cidade;
            private EstadosBrazil estado;
            private String CEP;*/
            String[] telefone = new String[3];
            telefone[0] = tField_telefone.getText();
            telefone[1] = tField_telefone.getText();
            telefone[2] = tField_telefone.getText();
            String tipoLogradouro = tField_TipoLogradouro.getText();
            String logradoro = tField_Logradouro.getText();
            String numero = tField_Numero.getText();
            String complemento = tField_Complemento.getText();
            String bairro = tField_Bairro.getText();
            String cidade = tField_Cidade.getText();
            String estado = cb_Estado.getSelectedItem().toString();
            String CEP = tField_CEP.getText();
            String email = tField_email.getText();
            EstadosBrazil eb = Enum.valueOf(EstadosBrazil.class, estado);

            Endereco endereco = new Endereco(tipoLogradouro, logradoro, numero, complemento, bairro, cidade, eb, CEP);
            if (jRadioButton_PessoaFisica.isSelected()) {
                String cpf = tField_cpf_cnpj.getText();
                String auxDataNascimento = tField_DataNascimento.getText();
                String[] vetDataNascimento = auxDataNascimento.split("/");
                Date dataNascimento = new Date(Integer.parseInt(vetDataNascimento[2]) - 1900, Integer.parseInt(vetDataNascimento[1]) - 1, Integer.parseInt(vetDataNascimento[0]));

                PessoaFisica clPF = new PessoaFisica(nome, cpf, dataNascimento, email, endereco, telefone);
                new ManipulaBancoPessoaFisica().incluir(clPF);
            }else
                if(jRadioButton_PessoaJuridica.isSelected())
                {
                    String cnpj = tField_cpf_cnpj.getText();
                    //String razaoSocial = t
                }

            //criando novo cliente com o id correspondente
            //Cliente_PessoaFisica clienteParaAdicionar = new Cliente_PessoaFisica(nome, cpf, endereco, telefone, email);
            //Cliente_PessoaFisica cliPF = new Cliente_PessoaFisica(nome, cpf, dataNascimento, telefone, email, endereco);
            StringBuffer saida = new StringBuffer("Cliente criado com sucesso");
            saida.append("Dados do novo cliente: ");
            //            saida.append(clienteParaAdicionar.getNome()).append("\n");
            //            saida.append(clienteParaAdicionar.getCpf()).append("\n");
            //            saida.append(clienteParaAdicionar.getTelefone()).append("\n");
            //            saida.append(clienteParaAdicionar.getEndereco()).append("\n");
            //            saida.append(clienteParaAdicionar.getEmail()).append("\n");

            //            listaClientes.add(clienteParaAdicionar);
            //tArea_saida.setText(String.valueOf(saida));
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_btn_criarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_criarCliente;
    private javax.swing.ButtonGroup buttonGroup_TipoPessoa;
    private javax.swing.JComboBox<EstadosBrazil> cb_Estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_CPF_CNPJ;
    private javax.swing.JLabel jLabel_DtNasc_RazSoc;
    private javax.swing.JRadioButton jRadioButton_PessoaFisica;
    private javax.swing.JRadioButton jRadioButton_PessoaJuridica;
    private javax.swing.JTextField tField_Bairro;
    private javax.swing.JTextField tField_CEP;
    private javax.swing.JTextField tField_Cidade;
    private javax.swing.JTextField tField_Complemento;
    private javax.swing.JTextField tField_DataNascimento;
    private javax.swing.JTextField tField_Logradouro;
    private javax.swing.JTextField tField_Numero;
    private javax.swing.JTextField tField_TipoLogradouro;
    private javax.swing.JTextField tField_cpf_cnpj;
    private javax.swing.JTextField tField_email;
    private javax.swing.JTextField tField_nome;
    private javax.swing.JTextField tField_telefone;
    private javax.swing.JTextField tField_telefone1;
    private javax.swing.JTextField tField_telefone2;
    // End of variables declaration//GEN-END:variables
 private void loadComboBox() {
        cb_Estado.setModel(new DefaultComboBoxModel<>(EstadosBrazil.values()));
    }
}
