/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.PessoaFisica;
import modelos.PessoaJuridica;
import modelos.Veiculo;
import modelos.auxiliares.MarcaVeiculo;
import modelos.auxiliares.ModeloVeiculo;
import persistencia.ManipulaBancoMarca;
import persistencia.ManipulaBancoModelos;
import persistencia.ManipulaBancoPessoaFisica;
import persistencia.ManipulaBancoPessoaJuridica;
import persistencia.ManipulaBancoVeiculo;

/**
 *
 * @author tanak
 */
public class TelaListaVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form TelaListaVeiculo
     */
    public TelaListaVeiculos() {
        initComponents();
        loadTableVeiculos("");
    }

    private void loadTableVeiculos(String busca) {
        try {
            ArrayList<Veiculo> listaVeiculos = new ManipulaBancoVeiculo().buscarTodos();
            DefaultTableModel table = (DefaultTableModel) jTableVeiculos.getModel();
            table.setRowCount(0);// * apagando linhas para não duplicar os dados da tabela

            ManipulaBancoPessoaFisica mbPf = new ManipulaBancoPessoaFisica();
            ManipulaBancoPessoaJuridica mbPj = new ManipulaBancoPessoaJuridica();
            ManipulaBancoMarca mbMarca = new ManipulaBancoMarca();
            ManipulaBancoModelos mbModelo = new ManipulaBancoModelos();
            for (Veiculo v : listaVeiculos) {
                if (v.getPlaca().contains(busca)) {//   * filtrando a busca
                    MarcaVeiculo marca = mbMarca.buscar(v.getIdMarca());
                    ModeloVeiculo modelo = mbModelo.buscar(v.getIdModelo());
                    if (marca != null && modelo != null) {//    * conferindo se a marca e o modelo existem
                        PessoaFisica pf = mbPf.buscar(v.getIdDonoVeiculo());
                        if (pf != null) {//  * vendo se é uma pessoa física
                            System.out.println(listaVeiculos.size());
                            table.addRow(new Object[]{pf.getNome(), v.getPlaca(), v.getChassi(), marca.getNomeMarca(), v.getRenavam(),
                                v.getTipoVeiculo(), v.getAnoFabricacao(), v.getAnoModelo(), modelo.getNomeModelo()});
                        } else {//  * tentar procurar por pessoa juridica
                            PessoaJuridica pj = mbPj.buscar(v.getIdDonoVeiculo());
                            if (pj != null) {//  * caso todos os dados estejam corretos
                                table.addRow(new Object[]{pj.getNomeFantasia(), v.getPlaca(), v.getChassi(), marca.getNomeMarca(), v.getRenavam(),
                                    v.getTipoVeiculo(), v.getAnoFabricacao(), v.getAnoModelo(), modelo.getNomeModelo()});
                            } else {
                                table.addRow(new Object[]{"veiculo sem dono", v.getPlaca(), v.getChassi(), marca.getNomeMarca(), v.getRenavam(),
                                    v.getTipoVeiculo(), v.getAnoFabricacao(), v.getAnoModelo(), modelo.getNomeModelo()});
                                System.out.println("veiculo sem dono: " + v);
// falha, o dono do veiculo não consta no banco de dados
                            }
                        }
                    } else {
                        table.addRow(new Object[]{"veiculo sem dono", v.getPlaca(), v.getChassi(), "marca não encontrada", v.getRenavam(),
                            v.getTipoVeiculo(), v.getAnoFabricacao(), v.getAnoModelo(), "modelo não encontrado"});
                        System.out.println("MArca/modelo não encontrado" + v.toString());
// falha, o modelo ou a marca não consta no banco de dados
                    }
                }
            }

        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVeiculos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Dono", "Placa", "Chassis", "Marca", "Renavan", "Tipo do veículo", "ano de fabricação", "Ano do modelo", "Modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableVeiculosKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVeiculos);

        jButton1.setText("Buscar dados do veículo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableVeiculosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableVeiculosKeyTyped
//        loadTableVeiculos(String.valueOf(evt.getKeyChar()));
    }//GEN-LAST:event_jTableVeiculosKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int indexLinhaSelecionadaNaTabela = jTableVeiculos.getSelectedRow();
            String placaVeiculo = "null";
            if (indexLinhaSelecionadaNaTabela >= 0) {
                placaVeiculo = String.valueOf(jTableVeiculos.getValueAt(indexLinhaSelecionadaNaTabela, 1));
            }
            int id = new ManipulaBancoVeiculo().buscar(placaVeiculo);
            System.out.println(id);
//            new TelaLIstaOSs(id).setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListaVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableVeiculos;
    // End of variables declaration//GEN-END:variables
}
