/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorEvent;
import javax.swing.table.DefaultTableModel;
import modelos.OrdemDeServico;
import modelos.Peca;
import modelos.Servico;
import persistencia.ManipulaBancoOrdemServico;
import persistencia.ManipulaBancoPecas;
import persistencia.ManipulaBancoServicos;

/**
 *
 * @author tanak
 */
public class TelaListaOS extends javax.swing.JInternalFrame {

    JDesktopPane telaAnterior;

    /**
     * Creates new form TelaListaOS
     *
     * @param telaAnterior
     */
    public TelaListaOS(JDesktopPane telaAnterior) {
        initComponents();
        this.telaAnterior = telaAnterior;
        loadTableOSs();
    }

    private void loadTableOSs() {
        try {

            DefaultTableModel table = (DefaultTableModel) jTableOSs.getModel();
            table.setRowCount(0);

            ArrayList<OrdemDeServico> listaOSs = null;
            listaOSs = new ManipulaBancoOrdemServico().buscarTodos();

            if (listaOSs != null && !listaOSs.isEmpty()) {//    * caso exista alguma OS para mostrar
                for (OrdemDeServico os : listaOSs) {
                    Servico servico = new ManipulaBancoServicos().buscar(os.getIdServico());
                    Peca peca = new ManipulaBancoPecas().buscar(os.getIdPeca());
                    String dataAbertura = new SimpleDateFormat("dd/MM/yyyy").format(os.getDataEntrada());
                    String dados[] = {String.valueOf(os.getCodigo()),// * código da OS
                        String.valueOf(os.getSituacao()),// * status da OS
                        servico.getNomeServico(),// * nome do serviço feito
                        String.valueOf(servico.getValorMaoDeObra()),//  * valor da mão de obra
                        dataAbertura,// * data de abertura da OS
                        "em aberto",//  * data de fechamento da OS
                        "-----",//  * código da peça usada
                        String.valueOf("0"),//  * quantidade de peças  usadas
                        String.valueOf("0"),//  * valor unitário da peça
                        String.valueOf(os.calcularValorTotalSemDesconto()),// * valor total da OS, sem desconto
                        String.valueOf(os.calcularValorTotalComDesconto())};// * valor total da OS, com desconto

                    if (os.getDataSaida() != null) {//  * já foi concluida
                        dados[5] = new SimpleDateFormat("dd/MM/yyyy").format(os.getDataSaida());

                    }
                    if (peca != null) {//   * usa alguma peça
                        dados[6] = peca.getCodigoPeca();//  * código da peça usada
                        dados[7] = String.valueOf(os.getQuantidadePeca());//  * quantidade de peças  usadas
                        dados[8] = String.valueOf(peca.getValorPeca());//  * valor unitário da peça
                        dados[9] = String.valueOf(os.calcularValorTotalSemDesconto());// * valor total da OS, sem desconto
                        dados[10] = String.valueOf(os.calcularValorTotalComDesconto());// * valor total da OS, com desconto
                    }
                    table.addRow(dados);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOSs = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTableOSs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Status", "Serviço feito", "mão de obra", "Data de abertura", "Data de fechamento", "Peça usada", "Quantidade usada", "Valor unitário", "Valor sem desconto", "Valor com desconto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableOSs);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(994, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(303, 303, 303))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (jTableOSs.getSelectedRow() < 0) {//    * não escolheu na tabela
                throw new Exception("selecione na tabela qual OS deseja pesquisar");
            }
            int idOSSelecionada = new ManipulaBancoOrdemServico().buscar("" + jTableOSs.getValueAt(jTableOSs.getSelectedRow(), 0));
            if (idOSSelecionada == 0) {
                throw new Exception("Falha ao carregar o id do objeto selecionado na tabela");
            }

            TelaBuscaOS tela = new TelaBuscaOS(idOSSelecionada);
            tela.setVisible(true);
            this.telaAnterior.add(tela);

            this.telaAnterior.remove(this);
            this.telaAnterior.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOSs;
    // End of variables declaration//GEN-END:variables
}
